### ISSUE TITLE
Request: graphana dashboard

### ISSUE THREAD

**Issue by LorCub** [dmeiners88/sonarqube-prometheus-exporter#1]
Hi guys,

Thanks for the amazing job.

Do you mind sharing the grafana dashboard xml? I would help a lot on setting this up quickly.

Regards,

Lorenzo

**Comment by leprechaun** [comment]
Here's what I got going: https://gist.github.com/leprechaun/8ac3b068cb7873ba3f30015026bdc2ec

**Comment by dmeiners88** [comment]
I also added the dashboard config that I used for the screenshot to the repo.
https://github.com/dmeiners88/sonarqube-prometheus-exporter/blob/develop/grafana_config.json
