### ISSUE TITLE
Improvements & releases

### ISSUE THREAD

**Issue by nox-404** [dmeiners88/sonarqube-prometheus-exporter#5]
Hello there,
is there any plan for future release/improvements ?
We'd like to get the number of line and duplication, is there a way to improve this ?
Also will it become available inside sonar's catalog ?

Best regards

**Comment by madhawadias** [comment]
You can add any metric you wish to get by simply adding it to the SUPPORTED_METRICS set in the PrometheusWebService.java file.
For example, if you wish to add Duplicated blocks, add the following line;
SUPPORTED_METRICS.add(CoreMetrics.DUPLICATED_BLOCKS);
for Number of lines of code add the following line;
SUPPORTED_METRICS.add(CoreMetrics.NCLOC);
![image](https://user-images.githubusercontent.com/30836762/56942513-c93bf080-6b38-11e9-8227-9a5291943894.png)
All the metrics you add here will be present in the admin panel of SonarQube as follows;
![image](https://user-images.githubusercontent.com/30836762/56942540-f6889e80-6b38-11e9-8799-45e95e398c66.png)

Hope this will help you.

**Comment by nox-404** [comment]
Thanks,
It would be preferable to be able to do this without altering the source file, but we'll try that
